version: "2"

services:
  db:
    image: "postgres:latest"
    container_name: "db"
    hostname: "db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db:5432
  irbisapp:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - FILEPATH_GENERATE=C:\\Users\\maksi\\Desktop\\irbisTest\\
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
